### ISSUE TITLE
Owner can take back control of contract after renouncing/transferring ownership

### ISSUE THREAD

**Issue by tmoux** [kyprox/kyprox_token#1]
I believe there is an issue with the Ownable contract, concerning the `lock` and `unlock` functions.
```
    //Locks the contract for owner for the amount of time provided
    function lock(uint256 time) public virtual onlyOwner {
        _previousOwner = _owner;
        _owner = address(0);
        _lockTime = now + time;
        emit OwnershipTransferred(_owner, address(0));
    }
    
    //Unlocks the contract for owner when _lockTime is exceeds
    function unlock() public virtual {
        require(_previousOwner == msg.sender, "You don't have permission to unlock");
        require(now > _lockTime , "Contract is locked until 7 days");
        emit OwnershipTransferred(_owner, _previousOwner);
        _owner = _previousOwner;
    }
```

Notice if the owner calls `lock(0)` and then calls `unlock()`, both `_owner` and `_previousOwner` will be set to the owner's address. If the owner then calls `renounceOwnership` or `transferOwnership`, he will no longer be the owner of the contract. However, he can then still call `unlock()` since the `_previousOwner` was not reset, forcibly taking back control of the contract. This would allow the owner to change parameters such as `_taxFee` and `_liquidityFee` when others have seen that the contract has been renounced and expect that the owner cannot do so.

I do not believe this is intended behavior, since `unlock` should only be allowed to be called when the contract is current locked. A simple solution would be to add the line `_previousOwner = address(0);` at the end of the `unlock` function, preventing it from being called when the contract is already unlocked.

**Comment by kyprox** [comment]
tmoux,
Thank you for your contribution. This issue has already been addressed to our team and will be fixed.
